/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ray_runtime_RayNativeRuntime */

#ifndef _Included_org_ray_runtime_RayNativeRuntime
#define _Included_org_ray_runtime_RayNativeRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ray_runtime_RayNativeRuntime
 * Method:    nativeInitCoreWorkerProcess
 * Signature:
 * (ILjava/util/Map;Ljava/lang/String;Ljava/lang/String;[BLorg/ray/runtime/gcs/GcsClientOptions;)J
 */
JNIEXPORT jlong JNICALL Java_org_ray_runtime_RayNativeRuntime_nativeInitCoreWorkerProcess(
    JNIEnv *, jclass, jint, jobject, jstring, jstring, jbyteArray, jobject);

/*
 * Class:     org_ray_runtime_RayNativeRuntime
 * Method:    nativeRunTaskExecutor
 * Signature: (JLorg/ray/runtime/task/TaskExecutor;)V
 */
JNIEXPORT void JNICALL Java_org_ray_runtime_RayNativeRuntime_nativeRunTaskExecutor(
    JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_ray_runtime_RayNativeRuntime
 * Method:    nativeDestroyCoreWorkerProcess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_ray_runtime_RayNativeRuntime_nativeDestroyCoreWorkerProcess(JNIEnv *, jclass,
                                                                     jlong);

/*
 * Class:     org_ray_runtime_RayNativeRuntime
 * Method:    nativeSetup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ray_runtime_RayNativeRuntime_nativeSetup(JNIEnv *, jclass,
                                                                         jstring);

/*
 * Class:     org_ray_runtime_RayNativeRuntime
 * Method:    nativeShutdownHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ray_runtime_RayNativeRuntime_nativeShutdownHook(JNIEnv *,
                                                                                jclass);

/*
 * Class:     org_ray_runtime_RayNativeRuntime
 * Method:    nativeSetCoreWorker
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_ray_runtime_RayNativeRuntime_nativeSetCoreWorker(
    JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
